version: '3'

tasks:
  default:
    deps: [lint, test, vet]

  build:
    desc: Build the go-mockslint binary
    cmds:
      - go build ./cmd/go-mockslint

  install:
    desc: Install go-mockslint globally
    cmds:
      - go install ./cmd/go-mockslint

  test:
    desc: Run tests with coverage
    cmds:
      - go test -v -cover ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  vet:
    desc: Run go vet with our custom analyzer
    deps: [build]
    cmds:
      - go vet -vettool=./go-mockslint ./...

  tidy:
    desc: Tidy and verify dependencies
    cmds:
      - go mod tidy
      - go mod verify

  ci:
    desc: Run all CI tasks
    deps: [tidy, lint, test, vet]

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f go-mockslint
      - go clean -cache -testcache 